remote:
  inference-web:
    driver: orderlyweb::orderlyweb_remote
    args:
      host: hiv-orderly.dide.ic.ac.uk
      port: 443
      prefix: inference-data
      token: $ORDERLYWEB_GITHUB_TOKEN
    primary: true
    default_branch: main
  fertility-web:
    driver: orderlyweb::orderlyweb_remote
    args:
      host: hiv-orderly.dide.ic.ac.uk
      port: 443
      prefix: fertility
      token: $ORDERLYWEB_GITHUB_TOKEN
    primary: false
    default_branch: main
    default_branch_only: true
  naomi-sharepoint:
    driver: orderly.sharepoint::orderly_remote_sharepoint
    args:
      url: https://imperiallondon.sharepoint.com
      site: HIVInferenceGroup-WP
      path: Shared Documents/orderly/naomi-orderly-naomi2
  fertility-sharepoint:
    driver: orderly.sharepoint::orderly_remote_sharepoint
    args:
      url: https://imperiallondon.sharepoint.com
      site: HIVInferenceGroup-WP
      path: Shared Documents/orderly/fertility

vault:
  addr: https://vault.dide.ic.ac.uk:8200

global_resources:
  global

minimum_orderly_version: 1.4.9
